
# set rule order for different cis results processing scripts
ruleorder: annotate_cis_results_dctap > annotate_cis_results_encode

configfile: "config/config.yml"
include: "rules/compute_heldout_indirect_effects_rate.smk"
include: "rules/calculate_direct_vs_effects.smk"

# perform all analyses
rule all:
  input:
    expand("results/{sample}/analyze_indirect_effects.html", sample = config["datasets"]),
    expand("results/{project}_analyses/model_indirect_effects.html", project = config["dataset_lists"]),
    expand("results/{project}_analyses/{type}_positive_hit_rates.tsv", type = ["cis", "trans"],
           project = config["dataset_lists"]),
    expand("results/annotated_crispr_data_encode/EPCrisprBenchmark_{dataset}_element_classes_direct_effects.tsv.gz",
           dataset = ["combined_training", "combined_heldout"]),
    "results/annotated_crispr_data_dctap/Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_and_merged_elements_fdr20_direct_effects.tsv"
