
# file containing TSS annotations to use for these analyses
tss_annot: "/oak/stanford/groups/engreitz/Users/agschwin/distal_regulation_paper/CRISPR_benchmarks/resources/genome_annotations/CollapsedGeneBounds.hg38.TSS500bp.bed"

# directory containing training data indirect analyses results
training_dir: "/oak/stanford/groups/engreitz/Users/agschwin/distal_regulation_paper/ENCODE_CRISPR_data/results"

# list of datasets for ENCODE and DC-TAP-seq paper analyses
dataset_lists:
  dctap: ["K562_DC_TAPseq_FDR20", "WTC11_DC_TAPseq_FDR20", "Klann2021", "Xie2019", "Morris2023_v1", "Morris2023_v2"]
  encode: ["K562_DC_TAPseq", "WTC11_DC_TAPseq", "Klann2021", "Xie2019", "Morris2023_v1", "Morris2023_v2"]

# input files and parameters for all datasets
datasets:
  K562_DC_TAPseq_FDR20:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/K562_DC_TAP_Seq/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/genome_annotation_files/gencode.v32lift37.annotation.gtf.gz"
    guide_assignment_method: "thresholding"
    guide_threshold: 5
    results: "resources/Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_and_merged_elements_fdr20.tsv"
    dist_threshold: 250000
  WTC11_DC_TAPseq_FDR20:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/WTC11_DC_TAP_Seq/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/genome_annotation_files/gencode.v32lift37.annotation.gtf.gz"
    guide_assignment_method: "thresholding"
    guide_threshold: 5
    results: "resources/Final_DC_TAP_Seq_Results_w_Chromatin_Categories_on_resized_and_merged_elements_fdr20.tsv"
    dist_threshold: 250000
  K562_DC_TAPseq:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/K562_DC_TAP_Seq/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/genome_annotation_files/gencode.v32lift37.annotation.gtf.gz"
    guide_assignment_method: "thresholding"
    guide_threshold: 5
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/K562_DC_TAP_Seq/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/formatted_dc_tap_results/results_with_element_gene_pair_categories.tsv"
    dist_threshold: 250000
  WTC11_DC_TAPseq:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/WTC11_DC_TAP_Seq/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/genome_annotation_files/gencode.v32lift37.annotation.gtf.gz"
    guide_assignment_method: "thresholding"
    guide_threshold: 5
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/process_validation_datasets/WTC11_DC_TAP_Seq/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/DC_TAP_Paper/results/formatted_dc_tap_results/results_with_element_gene_pair_categories.tsv"
    dist_threshold: 250000
  Klann2021:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Klann/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
    guide_assignment_method: "mixture"
    guide_threshold: Null
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Klann/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/create_encode_output/ENCODE/ENCODE_Klann_0.13gStd_Sceptre_perCRE_GRCh38.tsv.gz"
    dist_threshold: 250000
  Xie2019:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Xie/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
    guide_assignment_method: "mixture"
    guide_threshold: Null
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Xie/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/create_encode_output/ENCODE/ENCODE_Xie_0.13gStd_Sceptre_perCRE_GRCh38.tsv.gz"
    dist_threshold: 250000
  Morris2023_v1:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Morrisv1/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
    guide_assignment_method: "mixture"
    guide_threshold: Null
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Morrisv1/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/create_encode_output/ENCODE/ENCODE_Morrisv1_0.13gStd_Sceptre_perCRE_GRCh38.tsv.gz"
    dist_threshold: 250000
  Morris2023_v2:
    sceptre_object: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Morrisv2/differential_expression/sceptre_diffex_input.rds"
    genome: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/genome_annotation_files/gencode.v29.annotation.gtf.gz"
    guide_assignment_method: "mixture"
    guide_threshold: Null
    cis_results: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/process_validation_datasets/Morrisv2/differential_expression/results_run_discovery_analysis.rds"
    encode_file: "/oak/stanford/groups/engreitz/Users/jgalante/ENCODE_Sceptre_Analysis/results/create_encode_output/ENCODE/ENCODE_Morrisv2_0.13gStd_Sceptre_perCRE_GRCh38.tsv.gz"
    dist_threshold: 250000

# CRISPR benchmarking files for which to predict probability of direct vs indirect effects
crispr_benchmark_files:
  combined_training:
    file: "resources/training.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.WTC11_as_WTC11.reformatted.tsv.gz"
    dist_col: Null
  combined_heldout:
    file: "resources/validation_all.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.WTC11_as_WTC11.reformatted.tsv.gz"
    dist_col: Null
  dc_tap_subset: 
    file: "/oak/stanford/groups/engreitz/Users/sheth/ENCODE_rE2G_main/2025_0227_CTCF_and_H3K27ac/results/2025_0516_fix_peak_sizes/categorized_pairs/validation_DC_TAP.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.WTC11_as_WTC11.tsv.gz"
    dist_col: Null
  gasperini_sceptre_allPairs:
    file: "resources/Gasperini_all_power.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.reformatted.tsv.gz"
    dist_col: "distanceToTSS"
  gasperini_sceptre_filtPairs:
    file: "resources/Gasperini_DistalElementGene_SCEPTRE_well_powered.es15_over_80pct.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.reformatted.tsv.gz"
    dist_col: "distanceToTSS"  
  dc_tap_allPairs:
    file: "resources/all_dc_tap.h3k27me3_quantile_50.ratio_quantile_35.h3k27ac_quantiles_60_90.WTC11_as_WTC11.reformatted.tsv.gz"
    dist_col: "distanceToTSS"